spring:
  application:
    name:
      pass-batch
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/pass_local?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: pass_local_user
    password: passlocal
    hikari:
      maximum-pool-size: 20

  batch:
    jdbc:
      initialize-schema: always

logging:
  level:
    com.bodytok.pass: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
